### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties file.

spring.jmx:
   enabled: false

server:
  port: 9080
  contextPath: /orderman

#todo: make sure to always enable security in production
security:
  basic:
    enabled: false

#management endpoints on a separate port
management:
  port: 9081
  security:
    enabled: true # management port is internal only. no need to secure it.

#default project info followed by actual injected pom-specified values.
project:
  name: order-management-service
  version: 1.0
  description: Facilitates the configuration for Facilitator and Client.
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

    
database:
  packagesToScan: com.sr.om.dal.mysql.model
  hikari:
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    maximumPoolSize: 5
    maxLifetime: 30000
    idleTimeout: 30000
    autoCommit: false
    dataSourceProperties:
        url: jdbc:mysql://localhost:3306/sr_data
        user: root
        password: root
        prepStmtCacheSize: 256
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        cachePrepStmts: true
  hibernateProperties:
      hibernate.jdbc.batch_size: 4
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.generate_statistics: true
      hibernate.use_sql_comments: true
      hibernate.id.new_generator_mappings: false
      
database2:
  packagesToScan: com.sr.om.dal.mysql.model
  hikari:
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    maximumPoolSize: 5
    maxLifetime: 30000
    idleTimeout: 30000
    autoCommit: false
    dataSourceProperties:
        url: jdbc:mysql://localhost:3306/sr_data
        user: root
        password: root
        prepStmtCacheSize: 256
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        cachePrepStmts: true
  hibernateProperties:
      hibernate.jdbc.batch_size: 4
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.generate_statistics: true
      hibernate.use_sql_comments: true
      hibernate.id.new_generator_mappings: false
 



